export const fieldTooltips = {
  requested_order_id: "Request ID",
  item_code: "Item Code",
  item_name: "Item Name",
  item_name_requested: "Requested Item Name",
  quantity: "Quantity",
  unit: "Unit",
  priority: "Priority",
  requested_order_date: "Request Date",
  production_contract_number: "Production Contract Number",
  requester: "Requester",
  purchasing_manager: "Purchasing Manager",
  warehouse_deadline_date: "Warehouse Deadline",
  status: "Status",
  notes: "Notes",
  order_number: "Order Number",
  po_number: "PO Number",
  tracking_number: "Tracking Number",
  supplier_code: "SAP Supplier Code",
  shipping_method: "Shipping Method",
  etd: "Estimated Time of Departure",
  eta: "Estimated Time of Arrival",
  delay_days: "Delay Days",
  actual_entry_date: "Actual Warehouse Entry Date",
  task_name: "Task Name",
  assignee: "Assignee",
  created_by: "Created By",
  created_at: "Created At",
  assigned_at: "Assigned At",
  completed_at: "Completed At",
  role: "Role",
  task_status: "Task Status",
  actions: "Actions",
} as const
